[project]
name = "intro-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aarón Madera", email = "aaron.madera06@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "ruff>=0.16.5",
]

[project.scripts]
intro-ia = "intro_ia:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
