[project]
name = "docs-from-teacher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aarón Madera", email = "aaron.madera06@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "pyyaml==6.0",
]

[project.scripts]
docs-from-teacher = "docs_from_teacher:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
